# Generated by Django 4.2.5 on 2023-09-06 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attach",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp3"])
                        ],
                        verbose_name="添付ファイル",
                    ),
                ),
            ],
        ),
    ]
