# Generated by Django 4.2.5 on 2023-09-11 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kirinukiapp", "0002_question_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerateGif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gif_file", models.ImageField(upload_to="generated_gifs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="attach",
            field=models.FileField(
                upload_to="media/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp3", "avi", "mp4"])
                ],
                verbose_name="添付ファイル",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
